import { Component, Input, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';

interface Pattern { title: string; description: string; database: string; category: string; tags: string; sql: string; }
const PATTERNS: Pattern[] = [
  { title: 'Find a table or column', description: 'Search tables, views, and columns by name across the current database.', database: 'SQL Server', category: 'Schema', tags: 'table column search object metadata sys tables columns', sql: 'DECLARE @Search nvarchar(128) = N\'Customer\';\n\nSELECT\n    schema_name(t.schema_id) AS schema_name,\n    t.name AS table_name,\n    c.name AS column_name,\n    ty.name AS data_type,\n    c.max_length,\n    c.is_nullable\nFROM sys.tables AS t\nJOIN sys.columns AS c ON c.object_id = t.object_id\nJOIN sys.types AS ty ON ty.user_type_id = c.user_type_id\nWHERE t.name LIKE N\'%\' + @Search + N\'%\'\n   OR c.name LIKE N\'%\' + @Search + N\'%\'\nORDER BY schema_name, table_name, c.column_id;' },
  { title: 'Find table and column references', description: 'Find stored procedures, views, functions, and triggers that mention a table or column.', database: 'SQL Server', category: 'Dependencies', tags: 'reference references usage used by column table procedure view function trigger linkage', sql: 'DECLARE @Search nvarchar(256) = N\'CustomerId\';\n\nSELECT\n    schema_name(o.schema_id) AS schema_name,\n    o.name AS object_name,\n    o.type_desc\nFROM sys.sql_modules AS m\nJOIN sys.objects AS o ON o.object_id = m.object_id\nWHERE m.definition LIKE N\'%\' + @Search + N\'%\'\nORDER BY schema_name, object_name;' },
  { title: 'Show foreign-key relationships', description: 'List parents and children linked to a table, including the mapped columns.', database: 'SQL Server', category: 'Relationships', tags: 'foreign key fk relation relationship linkage parent child references', sql: 'DECLARE @Table sysname = N\'Orders\';\n\nSELECT\n    fk.name AS foreign_key_name,\n    schema_name(parent_table.schema_id) + N\'.\' + parent_table.name AS child_table,\n    parent_column.name AS child_column,\n    schema_name(referenced_table.schema_id) + N\'.\' + referenced_table.name AS parent_table,\n    referenced_column.name AS parent_column\nFROM sys.foreign_key_columns AS fkc\nJOIN sys.foreign_keys AS fk ON fk.object_id = fkc.constraint_object_id\nJOIN sys.tables AS parent_table ON parent_table.object_id = fkc.parent_object_id\nJOIN sys.columns AS parent_column ON parent_column.object_id = fkc.parent_object_id AND parent_column.column_id = fkc.parent_column_id\nJOIN sys.tables AS referenced_table ON referenced_table.object_id = fkc.referenced_object_id\nJOIN sys.columns AS referenced_column ON referenced_column.object_id = fkc.referenced_object_id AND referenced_column.column_id = fkc.referenced_column_id\nWHERE parent_table.name = @Table OR referenced_table.name = @Table\nORDER BY child_table, foreign_key_name;' },
  { title: 'List indexes and included columns', description: 'Inspect index keys, included columns, uniqueness, and disabled state for a table.', database: 'SQL Server', category: 'Indexes', tags: 'index indexes index usage keys included columns unique disabled table', sql: 'DECLARE @Table sysname = N\'Orders\';\n\nSELECT\n    i.name AS index_name,\n    i.type_desc,\n    i.is_unique,\n    i.is_primary_key,\n    i.is_disabled,\n    string_agg(CASE WHEN ic.is_included_column = 0 THEN c.name END, N\', \') WITHIN GROUP (ORDER BY ic.key_ordinal) AS key_columns,\n    string_agg(CASE WHEN ic.is_included_column = 1 THEN c.name END, N\', \') AS included_columns\nFROM sys.indexes AS i\nJOIN sys.index_columns AS ic ON ic.object_id = i.object_id AND ic.index_id = i.index_id\nJOIN sys.columns AS c ON c.object_id = ic.object_id AND c.column_id = ic.column_id\nJOIN sys.tables AS t ON t.object_id = i.object_id\nWHERE t.name = @Table\nGROUP BY i.name, i.type_desc, i.is_unique, i.is_primary_key, i.is_disabled\nORDER BY i.name;' },
  { title: 'Index usage statistics', description: 'Find seeks, scans, lookups, and updates for indexes since the last SQL Server restart.', database: 'SQL Server', category: 'Indexes', tags: 'index usage reads seeks scans lookups writes performance unused', sql: 'SELECT\n    schema_name(o.schema_id) AS schema_name,\n    o.name AS table_name,\n    i.name AS index_name,\n    coalesce(u.user_seeks, 0) AS seeks,\n    coalesce(u.user_scans, 0) AS scans,\n    coalesce(u.user_lookups, 0) AS lookups,\n    coalesce(u.user_updates, 0) AS updates,\n    u.last_user_seek,\n    u.last_user_scan\nFROM sys.indexes AS i\nJOIN sys.objects AS o ON o.object_id = i.object_id\nLEFT JOIN sys.dm_db_index_usage_stats AS u\n  ON u.database_id = db_id() AND u.object_id = i.object_id AND u.index_id = i.index_id\nWHERE o.type = N\'U\' AND i.index_id > 0\nORDER BY coalesce(u.user_seeks, 0) + coalesce(u.user_scans, 0) + coalesce(u.user_lookups, 0) DESC;' },
  { title: 'Find possibly unused indexes', description: 'Identify indexes with updates but no recorded reads. Review before removing because DMV data resets.', database: 'SQL Server', category: 'Indexes', tags: 'unused index write update delete drop performance', sql: 'SELECT\n    schema_name(o.schema_id) AS schema_name,\n    o.name AS table_name,\n    i.name AS index_name,\n    u.user_updates,\n    coalesce(u.user_seeks, 0) + coalesce(u.user_scans, 0) + coalesce(u.user_lookups, 0) AS user_reads\nFROM sys.indexes AS i\nJOIN sys.objects AS o ON o.object_id = i.object_id\nLEFT JOIN sys.dm_db_index_usage_stats AS u\n  ON u.database_id = db_id() AND u.object_id = i.object_id AND u.index_id = i.index_id\nWHERE o.type = N\'U\' AND i.index_id > 0\n  AND coalesce(u.user_updates, 0) > 0\n  AND coalesce(u.user_seeks, 0) + coalesce(u.user_scans, 0) + coalesce(u.user_lookups, 0) = 0\nORDER BY u.user_updates DESC;' },
  { title: 'Find orphaned foreign-key rows', description: 'Find child rows whose parent row does not exist.', database: 'SQL Server / PostgreSQL / MySQL', category: 'Data quality', tags: 'orphan missing parent foreign key integrity validation', sql: 'SELECT child.*\nFROM OrderItems AS child\nLEFT JOIN Orders AS parent ON parent.Id = child.OrderId\nWHERE parent.Id IS NULL;' },
  { title: 'Find duplicate business values', description: 'Find duplicate values that should be unique, optionally scoped by another column.', database: 'SQL Server / PostgreSQL / MySQL', category: 'Data quality', tags: 'duplicate duplicates unique constraint group having email', sql: 'SELECT Email, COUNT(*) AS duplicate_count\nFROM Users\nGROUP BY Email\nHAVING COUNT(*) > 1\nORDER BY duplicate_count DESC;' },
  { title: 'Reference or lookup data', description: 'Inspect distinct values and counts for a status, type, or reference column.', database: 'SQL Server / PostgreSQL / MySQL', category: 'Reference data', tags: 'reference lookup enum status type distinct values codes', sql: 'SELECT\n    Status,\n    COUNT(*) AS row_count\nFROM Orders\nGROUP BY Status\nORDER BY row_count DESC, Status;' },
  { title: 'Find rows missing required values', description: 'Check nullable or required business columns for empty values.', database: 'SQL Server / PostgreSQL / MySQL', category: 'Data quality', tags: 'null empty required missing validation data quality', sql: 'SELECT *\nFROM Customers\nWHERE Email IS NULL\n   OR NULLIF(LTRIM(RTRIM(Email)), N\'\') IS NULL;' },
  { title: 'Latest record per group', description: 'Return the newest row for each customer or other partition.', database: 'SQL Server / PostgreSQL', category: 'Window functions', tags: 'latest newest row per group customer row_number window', sql: 'WITH ranked AS (\n    SELECT\n        o.*,\n        ROW_NUMBER() OVER (PARTITION BY CustomerId ORDER BY CreatedAt DESC, Id DESC) AS row_number\n    FROM Orders AS o\n)\nSELECT *\nFROM ranked\nWHERE row_number = 1;' },
  { title: 'Find missing records', description: 'Find parent rows without matching children.', database: 'SQL Server / PostgreSQL / MySQL', category: 'Data quality', tags: 'missing no children anti join left join not exists', sql: 'SELECT c.*\nFROM Customers AS c\nWHERE NOT EXISTS (\n    SELECT 1\n    FROM Orders AS o\n    WHERE o.CustomerId = c.Id\n);' },
  { title: 'Safe upsert with existing key', description: 'Update a matching row or insert a new row inside a transaction.', database: 'SQL Server', category: 'Write operations', tags: 'upsert insert update merge transaction concurrency', sql: 'SET XACT_ABORT ON;\nBEGIN TRANSACTION;\n\nUPDATE Users\nSET DisplayName = @DisplayName\nWHERE Id = @Id;\n\nIF @@ROWCOUNT = 0\n    INSERT INTO Users (Id, DisplayName)\n    VALUES (@Id, @DisplayName);\n\nCOMMIT TRANSACTION;' },
  { title: 'Find active locks', description: 'Inspect current requests, blocking sessions, and wait information.', database: 'SQL Server', category: 'Diagnostics', tags: 'blocking locks blocked sessions wait deadlock troubleshooting', sql: 'SELECT\n    blocking_session_id,\n    session_id,\n    wait_type,\n    wait_time,\n    wait_resource,\n    status,\n    command,\n    text AS sql_text\nFROM sys.dm_exec_requests\nCROSS APPLY sys.dm_exec_sql_text(sql_handle)\nWHERE blocking_session_id <> 0\nORDER BY wait_time DESC;' },
  { title: 'Foreign keys without supporting indexes', description: 'Find foreign-key columns that may need an index for joins and deletes.', database: 'SQL Server', category: 'Indexes', tags: 'foreign key index performance join delete missing index', sql: 'SELECT\n    schema_name(t.schema_id) AS schema_name,\n    t.name AS table_name,\n    c.name AS foreign_key_column,\n    fk.name AS foreign_key_name\nFROM sys.foreign_key_columns AS fkc\nJOIN sys.foreign_keys AS fk ON fk.object_id = fkc.constraint_object_id\nJOIN sys.tables AS t ON t.object_id = fkc.parent_object_id\nJOIN sys.columns AS c ON c.object_id = fkc.parent_object_id AND c.column_id = fkc.parent_column_id\nWHERE NOT EXISTS (\n    SELECT 1\n    FROM sys.index_columns AS ic\n    WHERE ic.object_id = fkc.parent_object_id\n      AND ic.column_id = fkc.parent_column_id\n      AND ic.key_ordinal = 1\n);' }
];

@Component({
  selector: 'app-sql-search', standalone: true, imports: [FormsModule],
  templateUrl: './sql-search.html', styleUrls: ['./sql-search.css']
})
export class SqlSearch {
  @Input({ required: true }) instanceId!: string;
  query = '';
  results = signal(PATTERNS);
  search() {
    const terms = this.query.toLowerCase().split(/\s+/).filter(Boolean);
    if (!terms.length) {
      this.results.set(PATTERNS);
      return;
    }

    const ranked = PATTERNS.map(pattern => {
      const searchable = `${pattern.title} ${pattern.description} ${pattern.category} ${pattern.tags} ${pattern.database} ${pattern.sql}`.toLowerCase();
      const score = terms.reduce((total, term) => total + (searchable.includes(term) ? (pattern.title.toLowerCase().includes(term) ? 3 : 1) : 0), 0);
      return { pattern, score };
    }).filter(item => item.score === terms.length || item.score >= Math.max(1, terms.length - 1));

    this.results.set(ranked.sort((left, right) => right.score - left.score).map(item => item.pattern));
  }
}
